apiVersion: v1
kind: Secret
metadata:
  name: country-information-secret
  namespace: country-info
  labels:
    app: country-information
type: Opaque
stringData:
  DB_USERNAME: country
  DB_PASSWORD: country
